
package kbasefba;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * <p>Original spec-file type: GapfillingSolution</p>
 * <pre>
 * GapFillingSolution object holds data on a solution generated by gapfilling analysis
 * @optional objective gfscore actscore rejscore candscore rejectedCandidates activatedReactions failedReaction_refs
 * @searchable ws_subset id suboptimal integrated solutionCost koRestore_refs biomassRemoval_refs mediaSupplement_refs
 * </pre>
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("com.googlecode.jsonschema2pojo")
@JsonPropertyOrder({
    "id",
    "solutionCost",
    "biomassRemoval_refs",
    "mediaSupplement_refs",
    "koRestore_refs",
    "integrated",
    "suboptimal",
    "objective",
    "gfscore",
    "actscore",
    "rejscore",
    "candscore",
    "rejectedCandidates",
    "failedReaction_refs",
    "activatedReactions",
    "gapfillingSolutionReactions"
})
public class GapfillingSolution {

    @JsonProperty("id")
    private java.lang.String id;
    @JsonProperty("solutionCost")
    private Double solutionCost;
    @JsonProperty("biomassRemoval_refs")
    private List<String> biomassRemovalRefs;
    @JsonProperty("mediaSupplement_refs")
    private List<String> mediaSupplementRefs;
    @JsonProperty("koRestore_refs")
    private List<String> koRestoreRefs;
    @JsonProperty("integrated")
    private Long integrated;
    @JsonProperty("suboptimal")
    private Long suboptimal;
    @JsonProperty("objective")
    private Double objective;
    @JsonProperty("gfscore")
    private Double gfscore;
    @JsonProperty("actscore")
    private Double actscore;
    @JsonProperty("rejscore")
    private Double rejscore;
    @JsonProperty("candscore")
    private Double candscore;
    @JsonProperty("rejectedCandidates")
    private List<kbasefba.GapfillingReaction> rejectedCandidates;
    @JsonProperty("failedReaction_refs")
    private List<String> failedReactionRefs;
    @JsonProperty("activatedReactions")
    private List<ActivatedReaction> activatedReactions;
    @JsonProperty("gapfillingSolutionReactions")
    private List<kbasefba.GapfillingReaction> gapfillingSolutionReactions;
    private Map<java.lang.String, Object> additionalProperties = new HashMap<java.lang.String, Object>();

    @JsonProperty("id")
    public java.lang.String getId() {
        return id;
    }

    @JsonProperty("id")
    public void setId(java.lang.String id) {
        this.id = id;
    }

    public GapfillingSolution withId(java.lang.String id) {
        this.id = id;
        return this;
    }

    @JsonProperty("solutionCost")
    public Double getSolutionCost() {
        return solutionCost;
    }

    @JsonProperty("solutionCost")
    public void setSolutionCost(Double solutionCost) {
        this.solutionCost = solutionCost;
    }

    public GapfillingSolution withSolutionCost(Double solutionCost) {
        this.solutionCost = solutionCost;
        return this;
    }

    @JsonProperty("biomassRemoval_refs")
    public List<String> getBiomassRemovalRefs() {
        return biomassRemovalRefs;
    }

    @JsonProperty("biomassRemoval_refs")
    public void setBiomassRemovalRefs(List<String> biomassRemovalRefs) {
        this.biomassRemovalRefs = biomassRemovalRefs;
    }

    public GapfillingSolution withBiomassRemovalRefs(List<String> biomassRemovalRefs) {
        this.biomassRemovalRefs = biomassRemovalRefs;
        return this;
    }

    @JsonProperty("mediaSupplement_refs")
    public List<String> getMediaSupplementRefs() {
        return mediaSupplementRefs;
    }

    @JsonProperty("mediaSupplement_refs")
    public void setMediaSupplementRefs(List<String> mediaSupplementRefs) {
        this.mediaSupplementRefs = mediaSupplementRefs;
    }

    public GapfillingSolution withMediaSupplementRefs(List<String> mediaSupplementRefs) {
        this.mediaSupplementRefs = mediaSupplementRefs;
        return this;
    }

    @JsonProperty("koRestore_refs")
    public List<String> getKoRestoreRefs() {
        return koRestoreRefs;
    }

    @JsonProperty("koRestore_refs")
    public void setKoRestoreRefs(List<String> koRestoreRefs) {
        this.koRestoreRefs = koRestoreRefs;
    }

    public GapfillingSolution withKoRestoreRefs(List<String> koRestoreRefs) {
        this.koRestoreRefs = koRestoreRefs;
        return this;
    }

    @JsonProperty("integrated")
    public Long getIntegrated() {
        return integrated;
    }

    @JsonProperty("integrated")
    public void setIntegrated(Long integrated) {
        this.integrated = integrated;
    }

    public GapfillingSolution withIntegrated(Long integrated) {
        this.integrated = integrated;
        return this;
    }

    @JsonProperty("suboptimal")
    public Long getSuboptimal() {
        return suboptimal;
    }

    @JsonProperty("suboptimal")
    public void setSuboptimal(Long suboptimal) {
        this.suboptimal = suboptimal;
    }

    public GapfillingSolution withSuboptimal(Long suboptimal) {
        this.suboptimal = suboptimal;
        return this;
    }

    @JsonProperty("objective")
    public Double getObjective() {
        return objective;
    }

    @JsonProperty("objective")
    public void setObjective(Double objective) {
        this.objective = objective;
    }

    public GapfillingSolution withObjective(Double objective) {
        this.objective = objective;
        return this;
    }

    @JsonProperty("gfscore")
    public Double getGfscore() {
        return gfscore;
    }

    @JsonProperty("gfscore")
    public void setGfscore(Double gfscore) {
        this.gfscore = gfscore;
    }

    public GapfillingSolution withGfscore(Double gfscore) {
        this.gfscore = gfscore;
        return this;
    }

    @JsonProperty("actscore")
    public Double getActscore() {
        return actscore;
    }

    @JsonProperty("actscore")
    public void setActscore(Double actscore) {
        this.actscore = actscore;
    }

    public GapfillingSolution withActscore(Double actscore) {
        this.actscore = actscore;
        return this;
    }

    @JsonProperty("rejscore")
    public Double getRejscore() {
        return rejscore;
    }

    @JsonProperty("rejscore")
    public void setRejscore(Double rejscore) {
        this.rejscore = rejscore;
    }

    public GapfillingSolution withRejscore(Double rejscore) {
        this.rejscore = rejscore;
        return this;
    }

    @JsonProperty("candscore")
    public Double getCandscore() {
        return candscore;
    }

    @JsonProperty("candscore")
    public void setCandscore(Double candscore) {
        this.candscore = candscore;
    }

    public GapfillingSolution withCandscore(Double candscore) {
        this.candscore = candscore;
        return this;
    }

    @JsonProperty("rejectedCandidates")
    public List<kbasefba.GapfillingReaction> getRejectedCandidates() {
        return rejectedCandidates;
    }

    @JsonProperty("rejectedCandidates")
    public void setRejectedCandidates(List<kbasefba.GapfillingReaction> rejectedCandidates) {
        this.rejectedCandidates = rejectedCandidates;
    }

    public GapfillingSolution withRejectedCandidates(List<kbasefba.GapfillingReaction> rejectedCandidates) {
        this.rejectedCandidates = rejectedCandidates;
        return this;
    }

    @JsonProperty("failedReaction_refs")
    public List<String> getFailedReactionRefs() {
        return failedReactionRefs;
    }

    @JsonProperty("failedReaction_refs")
    public void setFailedReactionRefs(List<String> failedReactionRefs) {
        this.failedReactionRefs = failedReactionRefs;
    }

    public GapfillingSolution withFailedReactionRefs(List<String> failedReactionRefs) {
        this.failedReactionRefs = failedReactionRefs;
        return this;
    }

    @JsonProperty("activatedReactions")
    public List<ActivatedReaction> getActivatedReactions() {
        return activatedReactions;
    }

    @JsonProperty("activatedReactions")
    public void setActivatedReactions(List<ActivatedReaction> activatedReactions) {
        this.activatedReactions = activatedReactions;
    }

    public GapfillingSolution withActivatedReactions(List<ActivatedReaction> activatedReactions) {
        this.activatedReactions = activatedReactions;
        return this;
    }

    @JsonProperty("gapfillingSolutionReactions")
    public List<kbasefba.GapfillingReaction> getGapfillingSolutionReactions() {
        return gapfillingSolutionReactions;
    }

    @JsonProperty("gapfillingSolutionReactions")
    public void setGapfillingSolutionReactions(List<kbasefba.GapfillingReaction> gapfillingSolutionReactions) {
        this.gapfillingSolutionReactions = gapfillingSolutionReactions;
    }

    public GapfillingSolution withGapfillingSolutionReactions(List<kbasefba.GapfillingReaction> gapfillingSolutionReactions) {
        this.gapfillingSolutionReactions = gapfillingSolutionReactions;
        return this;
    }

    @JsonAnyGetter
    public Map<java.lang.String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperties(java.lang.String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public java.lang.String toString() {
        return ((((((((((((((((((((((((((((((((((("GapfillingSolution"+" [id=")+ id)+", solutionCost=")+ solutionCost)+", biomassRemovalRefs=")+ biomassRemovalRefs)+", mediaSupplementRefs=")+ mediaSupplementRefs)+", koRestoreRefs=")+ koRestoreRefs)+", integrated=")+ integrated)+", suboptimal=")+ suboptimal)+", objective=")+ objective)+", gfscore=")+ gfscore)+", actscore=")+ actscore)+", rejscore=")+ rejscore)+", candscore=")+ candscore)+", rejectedCandidates=")+ rejectedCandidates)+", failedReactionRefs=")+ failedReactionRefs)+", activatedReactions=")+ activatedReactions)+", gapfillingSolutionReactions=")+ gapfillingSolutionReactions)+", additionalProperties=")+ additionalProperties)+"]");
    }

}
